database:
  host: localhost
  port: 5432
  user: postgres
  password: rushtempest
  name: durich_db
  sslmode: disable
  timezone: Asia/Jakarta
server:
  port: 8081
  host: localhost

jwt:
  secret: rahasia-banget
  expiry: 24h

app:
  name: DURICH Backend
  version: 1.0.0
  environment: development

authentication:
  encrypt_key: "durich-encryption-key-32-bytes-long"
  access_secret_key: "durich-jwt-access-secret-key-development"
  refresh_secret_key: "durich-jwt-refresh-secret-key-development"
  issuer: "durich-system"
  access_token_expiry: 12h
  refresh_token_expiry: 168h

